steps:
  # Build the Docker image.
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '-t',
        'gcr.io/$$PROJECT_ID/workbench-custom:latest', 
        '.'  # Build context is the current directory.
    ]
  # Push the Docker image to Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'push',
        'gcr.io/$$PROJECT_ID/workbench-custom:latest'
    ]
images:
  - 'gcr.io/$$PROJECT_ID/workbench-custom:latest' #added for good practice